// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoWaHmm5F_SoISkVjjIgEEyUTdrv8fl5I',
    appId: '1:315799659527:web:8c7f7f7258993268d276a2',
    messagingSenderId: '315799659527',
    projectId: 'ditonton-d74da',
    authDomain: 'ditonton-d74da.firebaseapp.com',
    storageBucket: 'ditonton-d74da.firebasestorage.app',
    measurementId: 'G-VZ2K89QQ9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyWJEAFj_wIMBc91eX9lNwBtepChtmICs',
    appId: '1:315799659527:android:a48a47bae4b2571bd276a2',
    messagingSenderId: '315799659527',
    projectId: 'ditonton-d74da',
    storageBucket: 'ditonton-d74da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtw3X4yzPQVivre2hjzNAl4mZ8JFMm1uE',
    appId: '1:315799659527:ios:702ec092a0ad0d76d276a2',
    messagingSenderId: '315799659527',
    projectId: 'ditonton-d74da',
    storageBucket: 'ditonton-d74da.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
